// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Azure/operation-cache-controller/internal/handler (interfaces: RequirementHandlerInterface)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_requirement.go -package=mocks github.com/Azure/operation-cache-controller/internal/handler RequirementHandlerInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	reconciler "github.com/Azure/operation-cache-controller/internal/utils/reconciler"
	gomock "go.uber.org/mock/gomock"
)

// MockRequirementHandlerInterface is a mock of RequirementHandlerInterface interface.
type MockRequirementHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRequirementHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockRequirementHandlerInterfaceMockRecorder is the mock recorder for MockRequirementHandlerInterface.
type MockRequirementHandlerInterfaceMockRecorder struct {
	mock *MockRequirementHandlerInterface
}

// NewMockRequirementHandlerInterface creates a new mock instance.
func NewMockRequirementHandlerInterface(ctrl *gomock.Controller) *MockRequirementHandlerInterface {
	mock := &MockRequirementHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockRequirementHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequirementHandlerInterface) EXPECT() *MockRequirementHandlerInterfaceMockRecorder {
	return m.recorder
}

// EnsureCacheExisted mocks base method.
func (m *MockRequirementHandlerInterface) EnsureCacheExisted(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureCacheExisted", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureCacheExisted indicates an expected call of EnsureCacheExisted.
func (mr *MockRequirementHandlerInterfaceMockRecorder) EnsureCacheExisted(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureCacheExisted", reflect.TypeOf((*MockRequirementHandlerInterface)(nil).EnsureCacheExisted), ctx)
}

// EnsureCachedOperationAcquired mocks base method.
func (m *MockRequirementHandlerInterface) EnsureCachedOperationAcquired(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureCachedOperationAcquired", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureCachedOperationAcquired indicates an expected call of EnsureCachedOperationAcquired.
func (mr *MockRequirementHandlerInterfaceMockRecorder) EnsureCachedOperationAcquired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureCachedOperationAcquired", reflect.TypeOf((*MockRequirementHandlerInterface)(nil).EnsureCachedOperationAcquired), ctx)
}

// EnsureInitialized mocks base method.
func (m *MockRequirementHandlerInterface) EnsureInitialized(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureInitialized", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureInitialized indicates an expected call of EnsureInitialized.
func (mr *MockRequirementHandlerInterfaceMockRecorder) EnsureInitialized(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureInitialized", reflect.TypeOf((*MockRequirementHandlerInterface)(nil).EnsureInitialized), ctx)
}

// EnsureNotExpired mocks base method.
func (m *MockRequirementHandlerInterface) EnsureNotExpired(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureNotExpired", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureNotExpired indicates an expected call of EnsureNotExpired.
func (mr *MockRequirementHandlerInterfaceMockRecorder) EnsureNotExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureNotExpired", reflect.TypeOf((*MockRequirementHandlerInterface)(nil).EnsureNotExpired), ctx)
}

// EnsureOperationReady mocks base method.
func (m *MockRequirementHandlerInterface) EnsureOperationReady(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureOperationReady", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureOperationReady indicates an expected call of EnsureOperationReady.
func (mr *MockRequirementHandlerInterfaceMockRecorder) EnsureOperationReady(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureOperationReady", reflect.TypeOf((*MockRequirementHandlerInterface)(nil).EnsureOperationReady), ctx)
}
