// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Azure/operation-cache-controller/internal/handler (interfaces: OperationHandlerInterface)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_operation.go -package=mocks github.com/Azure/operation-cache-controller/internal/handler OperationHandlerInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	reconciler "github.com/Azure/operation-cache-controller/internal/utils/reconciler"
	gomock "go.uber.org/mock/gomock"
)

// MockOperationHandlerInterface is a mock of OperationHandlerInterface interface.
type MockOperationHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOperationHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockOperationHandlerInterfaceMockRecorder is the mock recorder for MockOperationHandlerInterface.
type MockOperationHandlerInterfaceMockRecorder struct {
	mock *MockOperationHandlerInterface
}

// NewMockOperationHandlerInterface creates a new mock instance.
func NewMockOperationHandlerInterface(ctrl *gomock.Controller) *MockOperationHandlerInterface {
	mock := &MockOperationHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockOperationHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperationHandlerInterface) EXPECT() *MockOperationHandlerInterfaceMockRecorder {
	return m.recorder
}

// EnsureAllAppsAreDeleted mocks base method.
func (m *MockOperationHandlerInterface) EnsureAllAppsAreDeleted(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureAllAppsAreDeleted", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureAllAppsAreDeleted indicates an expected call of EnsureAllAppsAreDeleted.
func (mr *MockOperationHandlerInterfaceMockRecorder) EnsureAllAppsAreDeleted(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureAllAppsAreDeleted", reflect.TypeOf((*MockOperationHandlerInterface)(nil).EnsureAllAppsAreDeleted), ctx)
}

// EnsureAllAppsAreReady mocks base method.
func (m *MockOperationHandlerInterface) EnsureAllAppsAreReady(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureAllAppsAreReady", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureAllAppsAreReady indicates an expected call of EnsureAllAppsAreReady.
func (mr *MockOperationHandlerInterfaceMockRecorder) EnsureAllAppsAreReady(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureAllAppsAreReady", reflect.TypeOf((*MockOperationHandlerInterface)(nil).EnsureAllAppsAreReady), ctx)
}

// EnsureFinalizer mocks base method.
func (m *MockOperationHandlerInterface) EnsureFinalizer(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureFinalizer", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureFinalizer indicates an expected call of EnsureFinalizer.
func (mr *MockOperationHandlerInterfaceMockRecorder) EnsureFinalizer(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureFinalizer", reflect.TypeOf((*MockOperationHandlerInterface)(nil).EnsureFinalizer), ctx)
}

// EnsureFinalizerRemoved mocks base method.
func (m *MockOperationHandlerInterface) EnsureFinalizerRemoved(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureFinalizerRemoved", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureFinalizerRemoved indicates an expected call of EnsureFinalizerRemoved.
func (mr *MockOperationHandlerInterfaceMockRecorder) EnsureFinalizerRemoved(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureFinalizerRemoved", reflect.TypeOf((*MockOperationHandlerInterface)(nil).EnsureFinalizerRemoved), ctx)
}

// EnsureNotExpired mocks base method.
func (m *MockOperationHandlerInterface) EnsureNotExpired(ctx context.Context) (reconciler.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureNotExpired", ctx)
	ret0, _ := ret[0].(reconciler.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureNotExpired indicates an expected call of EnsureNotExpired.
func (mr *MockOperationHandlerInterfaceMockRecorder) EnsureNotExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureNotExpired", reflect.TypeOf((*MockOperationHandlerInterface)(nil).EnsureNotExpired), ctx)
}
