# This rule is not used by the project operation-cache-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the controller.azure.github.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operation-cache-controller
    app.kubernetes.io/managed-by: kustomize
  name: cache-editor-role
rules:
- apiGroups:
  - controller.azure.github.com
  resources:
  - caches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controller.azure.github.com
  resources:
  - caches/status
  verbs:
  - get
