---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - app.github.com
  resources:
  - appdeployments
  - caches
  - operations
  - requirements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.github.com
  resources:
  - appdeployments/finalizers
  - caches/finalizers
  - operations/finalizers
  - requirements/finalizers
  verbs:
  - update
- apiGroups:
  - app.github.com
  resources:
  - appdeployments/status
  - caches/status
  - operations/status
  - requirements/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
  - patch
  - update
